name: titlecheck

on: 
  - pull_request_target

jobs:
  titlecheck:
    name: PR title follows coventional commit
    runs-on: ubuntu-latest
    steps:
    - name: Check conventinal title
      uses: aslafy-z/conventional-pr-title-action@master
      with:
        success-state: Title follows the specification.
        failure-state: Title does not follow the specification. See https://www.conventionalcommits.org/en/v1.0.0/
        context-name: conventional-pr-title
        preset: conventional-changelog-angular@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}